version: '3.5'
#configs:
# ms-api-config:
#    file: /opt/clikenv/ekyc/clik.env
# haproxy-dev:
#    file: /opt/clikenv/ekyc/clik-test.pem
# cert-file:
#    file: /opt/clikenv/ekyc/clicert.pfx
# welcome-page:
#    file: /opt/clikenv/ekyc/index.http
services:
        
  app1:
    image: oudamdevops/app1:2.0.0
    ports:
      - 6001:8080
    deploy:
      mode: global
       #replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  app2:
    image: oudamdevops/app2:2.0.0
    ports:
      - 6002:8080
    deploy:
      mode: global
      #replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  app3:
    image: oudamdevops/app3:2.0.0
    ports:
      - 6003:8080
    deploy:
      mode: global
      #replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  haproxy:
    ports:
      - "80:80"
    image: oudamdevops/haproxy:2.0.0
    deploy:
      mode: global
      update_config:
        parallelism: 1

